---
- name: Create directory parity_data/keys/NetworkName
  file:
    path: "{{ home }}/parity_data/keys/{{ GENESIS_NETWORK_NAME }}"
    state: directory
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create logs directories
  file:
    path: "/{{ home }}/logs/old"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- git: repo=https://github.com/{{ POANETWORK_REPO_FETCH }}/eth-net-intelligence-api dest={{ home }}/eth-net-intelligence-api

- name: Install netstats config
  template: src=app.json.j2 dest={{ home }}/eth-net-intelligence-api/app.json owner={{ username }} group={{ username }} mode=0644
  notify:
    - restart poa-netstats

- file: path={{ home }}/eth-net-intelligence-api owner={{ username }} group={{ username }} recurse=yes

- name: install npm netstats
  shell: "cd /home/{{ username }}/eth-net-intelligence-api; /usr/bin/npm install"
  become: true
  become_user: "{{ username }}"
  notify:
    - restart poa-netstats


- name: Install poa-netstats service
  template: src=poa-netstats.j2 dest=/etc/systemd/system/poa-netstats.service owner=root group=root mode=0755
  notify:
    - restart poa-netstats

- name: Ensure poa-netstats is running and enabled to start at boot
  service: name=poa-netstats state=started enabled=yes
